<a href="https://colab.research.google.com/github/Rut092/rut-ai-portfolio-PHASE2-DL/blob/main/Perceptron_neural_network(Mnist_dataset).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [ ]:
# Create an instance of our Network (using the corrected __init__ and feedforward)
net = [2, 3, 1]

# Define an example input 'a'.
# For sizes=[2, 3, 1], the input layer has 2 neurons.
# So, 'a' should be a column vector of shape (2, 1).
input_a = np.array([[0.5], [0.8]])
# Example input values"

print("Input 'a' to feedforward:\n", input_a)
print("Input 'a' shape:", input_a.shape)


Input 'a' to feedforward:
 [[0.5]
 [0.8]]
Input 'a' shape: (2, 1)


In [ ]:
network_sizes = [2, 3, 1]
print(f"Network architecture (sizes): {network_sizes}\n")

# Correct initialization for weights:
# Weights connect a layer with 'x' neurons to a layer with 'y' neurons.
# So, the weight matrix for this connection should have shape (y, x).
# zip(sizes[:-1], sizes[1:]) pairs up (input_layer_size, output_layer_size) for each connection.
# For sizes=[2, 3, 1]:
#   - First connection: x=2 (input), y=3 (first hidden) -> weight_matrix_1 shape (3, 2)
#   - Second connection: x=3 (first hidden), y=1 (output) -> weight_matrix_2 shape (1, 3)

correct_weights_example = [np.random.randn(y, x) for x, y in zip(network_sizes[:-1], network_sizes[1:])]

print("Correctly initialized weights (list of NumPy arrays):\n")
for i, arr in enumerate(correct_weights_example):
    print(f"Weight matrix {i+1} (connecting layer {network_sizes[i]} to layer {network_sizes[i+1]}, shape {arr.shape}):\n{arr}\n")

print("#################################################")
print("Summary of correct_weights_example structure:")
print(f"Number of weight matrices: {len(correct_weights_example)}")
for i, arr in enumerate(correct_weights_example):
    print(f"  Matrix {i+1} shape: {arr.shape}")

print("\n#################################################")
print("Demonstrating Weight Matrix Multiplication with Input:\n")

# Let's take the first weight matrix (W1) and an example input (a0)
W1 = correct_weights_example[0] # Shape (3, 2)
input_a0 = np.array([[0.5], [0.8]]) # Example input, shape (2, 1)

print(f"First Weight Matrix (W1) shape: {W1.shape}\n{W1}\n")
print(f"Input Vector (a0) shape: {input_a0.shape}\n{input_a0}\n")

# Perform the matrix multiplication: W1 * a0
# The number of columns in W1 (2) must match the number of rows in a0 (2).
# The result will have the number of rows of W1 (3) and columns of a0 (1).

# Each row of W1 represents the weights for a neuron in the next layer.
# Each column of a0 represents an input feature.

# For example, if W1 is:
# [[w11, w12],
#  [w21, w22],
#  [w31, w32]]

# And a0 is:
# [[x1],
#  [x2]]

# Then W1 * a0 will be:
# [[w11*x1 + w12*x2],
#  [w21*x1 + w22*x2],
#  [w31*x1 + w32*x2]]

output_z1 = np.dot(W1, input_a0)

print(f"Result of W1 @ a0 (output_z1) shape: {output_z1.shape}\n{output_z1}\n")
print("This output vector (output_z1) of shape (3, 1) then gets a bias added to it,")
print("and then the sigmoid activation function is applied element-wise to produce the activations")
print("(a1) for the next layer. This a1 then becomes the input for the next weight matrix multiplication.")

Network architecture (sizes): [2, 3, 1]

Correctly initialized weights (list of NumPy arrays):

Weight matrix 1 (connecting layer 2 to layer 3, shape (3, 2)):
[[ 0.86651911 -0.98218818]
 [ 0.40459711 -1.7238475 ]
 [ 0.83675861  0.58505602]]

Weight matrix 2 (connecting layer 3 to layer 1, shape (1, 3)):
[[-0.44507392  1.47394363  1.05096044]]

#################################################
Summary of correct_weights_example structure:
Number of weight matrices: 2
  Matrix 1 shape: (3, 2)
  Matrix 2 shape: (1, 3)

#################################################
Demonstrating Weight Matrix Multiplication with Input:

First Weight Matrix (W1) shape: (3, 2)
[[ 0.86651911 -0.98218818]
 [ 0.40459711 -1.7238475 ]
 [ 0.83675861  0.58505602]]

Input Vector (a0) shape: (2, 1)
[[0.5]
 [0.8]]

Result of W1 @ a0 (output_z1) shape: (3, 1)
[[-0.35249099]
 [-1.17677945]
 [ 0.88642412]]

This output vector (output_z1) of shape (3, 1) then gets a bias added to it,
and then the sigmoid activation fu

In [ ]:
class Network:
    def __init__(self,sizes):
        self.num_layers=len(sizes)
        self.sizes=sizes
        self.weights = [np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])]
        self.biases = [np.random.randn(y, 1) for y in sizes[1:]]

    def sigmoid(self,x):
        return 1/(1+np.exp(-x))

    def sigmoid_prime(self,x):
        return self.sigmoid(x)*(1-self.sigmoid(x))

    def cost_function(self,output,y):
        return output-y

    def feedforward(self,a):
        """Return the output of the network if `a` is input."""
        # `a` represents the input activations to the network.
        for b,w in zip(self.biases,self.weights):
            a =  self.sigmoid(np.dot(w,a)+b)
            # a = 2x1 input => 3x1 => 1x1
        return a

    def SGD(self,training_data,epochs,mini_batch_size,eta,test_data=None):
        if test_data: n_test = len(test_data)
        n= len(training_data)
        for epoch in range(epochs):
            random.shuffle(training_data)
            mini_batches = [training_data[k:k+mini_batch_size] for k in range(0,n,mini_batch_size)]
            for batch in mini_batches:
                self.update_mini_batch(batch,eta)

            if test_data:
                print(f"Epoch {epoch}: {self.evaluate(test_data)} / {n_test}")
            else:
                print(f"Epoch {epoch} complete")

    def update_mini_batch(self,batch,eta):

        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]

        for x,y in batch:
            delta_nabla_b,delta_nabla_w = self.backprop(x,y)
            # Accumulate gradients (nabla_b, nabla_w from backprop were actually delta_nabla_b, delta_nabla_w)
            nabla_b = [nb+dnb for nb,dnb in zip(nabla_b,delta_nabla_b)]
            nabla_w = [nw+dnw for nw,dnw in zip(nabla_w,delta_nabla_w)]

        self.weights = [w-(eta/len(batch))*nw for w,nw in zip(self.weights,nabla_w)]
        self.biases =  [b-(eta/len(batch))*nb for b,nb in zip(self.biases,nabla_b)]

    def backprop(self,x,y):
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]

        activation = x
        activations = [x]

        zs = []
        for b,w in zip(self.biases,self.weights):
            z = np.dot(w,activation)+b
            zs.append(z)

            activation = self.sigmoid(z)
            activations.append(activation)

        # backward pass
        # l = 1 means the last layer of neurons, l = 2 is the
        # second-last layer, and so on.

        delta = self.cost_function(activations[-1],y) * self.sigmoid_prime(zs[-1])
        nabla_b[-1] = delta
        nabla_w[-1] = np.dot(delta,activations[-2].transpose()) # Transpose of activation[-2]

        # we did it for 1 now we are doing it for rest of the set
        # because 1st layer is output set thats why we didnt include it into the loop

        for i in range(2,self.num_layers):
            # The `i`th layer means `-(i)` for indexing from the end.
            # The weight matrix connecting layer `l-1` to `l` is `self.weights[l-1]`.
            # For delta in layer `l`, we multiply by transpose of weight matrix connecting `l` to `l+1`.
            # This means `self.weights[-(i-1)]` or `self.weights[-i+1]` as it is written.
            delta = np.dot(self.weights[-i+1].transpose(),delta) * self.sigmoid_prime(zs[-i])
            nabla_b[-i] = delta
            nabla_w[-i] = np.dot(delta,activations[-i-1].transpose()) # Transpose of activation[-i-1]

        return (nabla_b,nabla_w)

    def evaluate(self,test_data):
        # For evaluation, we only care about the class with the highest probability
        test_results = [(np.argmax(self.feedforward(x)), np.argmax(y)) # y is now one-hot encoded
                        for (x,y) in test_data]
        return sum(int(x==y) for (x,y) in test_results)

The Weight Matrix (W): Needs to be a 2x3 grid (2 rows, 3 columns) because there are 6 total connections between the layers. The Error Vector (delta): Is a vertical column of 2 numbers (one error for each output neuron). Shape: $(2 \times 1)$. The Activation Vector (a_prev): Is a vertical column of 3 numbers (one for each previous neuron). Shape: $(3 \times 1)$. How do you multiply a $(2 \times 1)$ column and a $(3 \times 1)$ column to magically create a $(2 \times 3)$ grid of weight updates? You transpose the activation vector! If you lay $a_{prev}$ flat on its side, its shape becomes $(1 \times 3)$. Now, when you do the dot product: $(2 \times 1) \cdot (1 \times 3) = (2 \times 3) \text{ Matrix}$

## Now Back to training the Dataset

In [ ]:
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Reshape and normalize x_train and x_test
x_train_reshaped = [np.reshape(x, (784, 1)) / 255.0 for x in x_train]
x_test_reshaped = [np.reshape(x, (784, 1)) / 255.0 for x in x_test]

# One-hot encode y_train and y_test using OneHotEncoder
# Reshape y_train and y_test to be 2D arrays (samples, 1) for OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# Use fit_transform for y_train
y_train_encoded_raw = encoder.fit_transform(y_train.reshape(-1, 1))

# Use transform for y_test to apply the same mapping learned from y_train
y_test_encoded_raw = encoder.transform(y_test.reshape(-1, 1))

# Reshape the one-hot encoded arrays to a list of (10, 1) column vectors
y_train_encoded = [vec.reshape(10, 1) for vec in y_train_encoded_raw]
y_test_encoded = [vec.reshape(10, 1) for vec in y_test_encoded_raw]

print(y_train_encoded_raw.shape,y_train_encoded[0].shape)
print(y_test_encoded_raw[:3],y_test_encoded[:3])

# Combine into training_data and test_data
training_data = list(zip(x_train_reshaped, y_train_encoded))
test_data = list(zip(x_test_reshaped, y_test_encoded))

(60000, 10) (10, 1)
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]] [array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.]]), array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]]), array([[0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])]


Now, let's inspect the shapes of a sample from the transformed `training_data` to ensure they match the expected format for your `Network` class.

In [ ]:
print(f"Shape of first training image input (x): {training_data[0][0].shape}")
print(f"Shape of first training label output (y): {training_data[0][1].shape}")

print(f"Number of training samples: {len(training_data)}")
print(f"Number of test samples: {len(test_data)}")

Shape of first training image input (x): (784, 1)
Shape of first training label output (y): (10, 1)
Number of training samples: 60000
Number of test samples: 10000


In [ ]:
net = Network([784, 30, 10])
net.SGD(training_data, epochs=10, mini_batch_size=10, eta=3.0, test_data=test_data)

Epoch 0: 9127 / 10000
Epoch 1: 9302 / 10000
Epoch 2: 9301 / 10000
Epoch 3: 9360 / 10000
Epoch 4: 9400 / 10000
Epoch 5: 9452 / 10000
Epoch 6: 9432 / 10000
Epoch 7: 9487 / 10000
Epoch 8: 9499 / 10000
Epoch 9: 9503 / 10000
